### ISSUE TITLE
Console undefined

### ISSUE THREAD

**Issue by cesco69** [pawelczak/EasyAutocomplete#115]
In IE8 (probably earlier versions too) I get script errors saying 'console' is undefined.

**Comment by tobybowers** [comment]
In IE8 the console object isn't created until you open DevTools, this is what will be causing your error. If you have to support IE8 (or earlier) i'd suggest reading the following:

http://stackoverflow.com/a/14246240/799588

**Comment by pawelczak** [comment]
I'm thinking about supporting IE8 for some time and I'm kinda tore. Because I don't want to add code only for one, really bad, old and not used browser. 

Other thing is that this problem should not be resolved by plugin itself. More in the link presented above by **tobybowers**.

BTW who uses IE8?(Who knows how  to use computer)
http://gs.statcounter.com/#all-browser_version_partially_combined-ww-monthly-201409-201509-bar
