### ISSUE TITLE
Autocomplete on dynamically generated input elements

### ISSUE THREAD

**Issue by nineonine** [pawelczak/EasyAutocomplete#126]
Is it possible to make it work on fields which are added later on ?

Now it only works on the field which was rendered on page load.

thanks !

**Comment by pawelczak** [comment]
It should work.. 

This is an interesting concept, that I haven't tested out. I'll write some tests for it and we will see, if plugin works correctly.

**Comment by pawelczak** [comment]
Plugin works with dynamic generated input fields.

**Comment by nineonine** [comment]
maybe I had this issue because my inputs had the same id

**Comment by pawelczak** [comment]
Yup, that is probably what caused problems for you. Keep in mind, that having two elements with the same id is a bad practice.

**Comment by pimplesushant** [comment]
I have cloned a div withb .clone() and generated ids needed for easyautocomplete() dymically. 

the ajax function and prepareData works fine but onSelectItemEvent doesn't populate list hence couldn't perform further actions.

**Comment by madedev06** [comment]
Good please an example with dynamic input please, since I have a code which I insert new row to a html table which easyautocomplete plugin does not recognize its id and therefore does not generate the expected results.
But if in return I put this input to start the page there if easyautocomplete recognizes it and it works completely. thanks.
